url:
  #自定义交付家Url
  customDeliveryUrl : http://localhost:20004/mdvn-template/templates/customDelivery
  #获取创建人Url
  retrieveMembersUrl : http://localhost:20001/mdvn-staff/staff/retrieveTerseInfo
  #获取交付件Url
  retrieveDeliveryUrl : http://localhost:20004/mdvn-template/templates/retrieveDelivery


